repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.9
    hooks:
      - id: ruff
        args: [ --fix ]
      - id: ruff-format

  - repo: local
    hooks:
      - id: update-requirements
        name: Update requirements.txt
        entry: python -c "import subprocess; subprocess.run('poetry export --without-hashes --format=requirements.txt', shell=True, check=True, stdout=open('requirements.txt', 'w'))"
        language: system
        types: [file]
        files: ^(?:poetry\.lock|pyproject\.toml)$
