name: Add Reviewer

on:
  pull_request:
    types: [opened]

jobs:
  add-reviewer:
    runs-on: ubuntu-latest
    
    steps:
    - name: Add reviewer
      uses: octokit/request-action@v2.x
      with:
        route: POST /repos/:owner/:repo/pulls/:pull_number/requested_reviewers
        owner: ${{ github.repository_owner }}
        repo: ${{ github.event.repository.name }}
        pull_number: ${{ github.event.pull_request.number }}
        reviewers: LIfeAdventurer
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
